---
Name: iqformbuilderpayments
---
IQnection\FormBuilder\FormBuilder:
  extensions:
    - 'IQnection\FormBuilderPayments\Extensions\FormBuilderPayments'
IQnection\FormBuilder\Model\Submission:
  extensions:
    - 'IQnection\FormBuilderPayments\Extensions\SubmissionExtension'
